format = """
[î‚¶](#a3aed2)\
$username\
$hostname\
[î‚´](bg:#769ff0 fg:#a3aed2)\
$directory\
[î‚´](fg:#769ff0 bg:#565f89)\
$git_branch\
$git_status\
[î‚´](fg:#565f89 bg:#394260)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[î‚´](fg:#394260 bg:#212736)\
$docker_context\
$aws\
$azure\
$nix_shell\
$terraform\
$pulumi\
[î‚´](fg:#212736 bg:#1d2230)\
$time\
[î‚´ ](fg:#1d2230)\
"""

command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#a3aed2 fg:#090c0c"
style_root = "bg:#3B4252"
format = '[$user ]($style)'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

# ~/.config/starship.toml

[hostname]
ssh_only = true
style = "bg:#a3aed2 fg:#090c0c"
# style = "bg:#212736 fg:#bb9af7"
format = '[|$ssh_symbol]($style)[ $hostname ]($style)'
trim_at = '.companyname.com'

[c]
symbol = "î˜ "
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#212736 fg:#bb9af7"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = "î‰µ "
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï„“"
style = "bg:#565f89"
format = '[[ $symbol $branch ](fg:#7aa2f7 bg:#565f89)]($style)'

[git_status]
style = "bg:#565f89"
format = '[[($all_status$ahead_behind )](fg:#7aa2f7 bg:#565f89)]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#394260"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = "î¨"
style = "bg:#394260"
format = '[ $symbol ($version) ]($style)'

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = 'ó° … '
style = "bg:#212736 fg:#bb9af7"

[aws]
format = 'on [$symbol$profile]($style) '
style = "bg:#212736 fg:#bb9af7"
symbol = 'ğŸ…° '
[aws.profile_aliases]
enterprise_naming_scheme-voidstars = 'void**'

[nix_shell]
disabled = true
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
style = "bg:#212736 fg:#bb9af7"
format = '[â˜ƒï¸ $state( \($name\))]($style) '

[terraform]
style = "bg:#212736 fg:#bb9af7"
format = '[ğŸğŸ’¨ $workspace]($style) '

[pulumi]
symbol = 'ğŸ›¥ '
style = "bg:#212736 fg:#bb9af7"
format = '[$symbol$stack]($style) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[ $time ]($style)'
